### ISSUE TITLE
Please add a github release for version 0.7.1

### ISSUE THREAD

**Issue by bb-Ricardo** [joni1993/icinga2apic#1]
Hi,

first of all, thank you for taking this matter in your own hands. at least there is progress now.

Would be great to see a release on github in https://github.com/joni1993/icinga2apic/releases.

Thank you

**Comment by joni1993** [comment]
You can find the new release here:
https://github.com/joni1993/icinga2apic/releases/tag/0.7.1

Is there any specific reason you prefer GitHub releases over PyPi (https://pypi.org/project/icinga2apic/0.7.1/) ones?

**Comment by bb-Ricardo** [comment]
A few reasons which help me to keep track of what's happening to projects
1. that you can see there is a new release directly on GitHub.
2. what has changed between the releases and you can simple diff them. Compared to this: https://pypi.org/project/icinga2apic/0.7.1/#history
3. and this: https://pypi.org/help/#project-release-notifications
