### ISSUE TITLE
actions.acknowledge_problem() persistent flag

### ISSUE THREAD

**Issue by tomabg** [joni1993/icinga2apic#3]
Hi,

is this project still maintained?
would it be possible to add persisten flag in actions.acknowledge_problem()

the parameter is available in API for acknowledge-problem:

persistent | Boolean | Optional. When the comment is of type Acknowledgement and this is set to true, the comment will remain after the acknowledgement recovers or expires. Defaults to false.
-- | -- | --

**Comment by joni1993** [comment]
Hi, i will take a look into this.

**Comment by joni1993** [comment]
I am slightly confused - the persistent flag is not part of "add_comment" but only of "acknowledge-problem".

I will try to add an additional parameter for "optional" arguments.

**Comment by tomabg** [comment]
Hi,

yes because a comment is always persistent...the sence behind is ..if the service switch back to OK an acknowledgement comment will disapear by default...to avoid this the persistent flag can be used

**Comment by tomabg** [comment]
corrected title you are fully right acknowledge_problem should have persistent flag
sorry

**Comment by joni1993** [comment]
The method actually has a parameter for the persistent-flag:
https://github.com/joni1993/icinga2apic/blob/master/icinga2apic/actions.py#L264

**Comment by tomabg** [comment]
oh sorry you are fully right...just tested it again and its working...probably update DOKU
