### ISSUE TITLE
process_check_result filter?

### ISSUE THREAD

**Issue by Bierchermuesli** [joni1993/icinga2apic#4]
It looks like [process_check_result](https://github.com/joni1993/icinga2apic/blob/d964e1d978e4c8d137edd501f4aa19040d10cb8e/icinga2apic/actions.py#L48) missing the `filter_vars` and `filters` params. Is there a reason for omitting?

see [Icinga API Documentation](https://icinga.com/docs/icinga-2/latest/doc/12-icinga2-api/#process-check-result)

If you need help, i can give a try with an PR

Thanks

**Comment by joni1993** [comment]
Hi,
I don't see a reason why they are missing.
Feel free to submit a PR - I will also have look on it.

**Comment by Bierchermuesli** [comment]
noice, thanks!
