### ISSUE TITLE
Multiple filters - how

### ISSUE THREAD

**Issue by kajla** [joni1993/icinga2apic#5]
Hello,

Not completely clear that how to concatenate filters.
How do I give multiple filters to events?

Thank you in advance.

**Comment by joni1993** [comment]
Hi,
you can find instruction on how the filters work on the official Icinga2 API docs: https://icinga.com/docs/icinga-2/latest/doc/12-icinga2-api/#advanced-filters

A short example for icinga2apic:
```api_client.actions.process_check_result("Host",None,1,"test output",filters="host.name == filterHost || host.name == filterHost2 ",filter_vars={"filterHost":"myFirstHost","filterHost2":"mySecondHost"})```
This would sent a passive check results with state "CRITICAL" for the two hosts `myFirstHost` and `mySecondHost`.
